apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ./appprojects/
  - ./appsets/
  - namespace.yaml

helmCharts:
  - repo: https://argoproj.github.io/argo-helm
    name: argo-cd
    releaseName: argocd
    namespace: argocd
    version: 8.0.12
    valuesFile: values.yaml
