apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-b
spec:
  description: ArgoCD project for Team-B apps
  destinations:
    - namespace: '!default'
      server: '*'
  sourceRepos:
    - '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  # orphanedResources:
  #   warn: true
