apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx

resources:
  - namespace.yaml

helmCharts:
  - repo: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    releaseName: ingress-nginx
    namespace: ingress-nginx
    version: 4.13.0
    valuesFile: values.yaml
